name: Build
on:
  push:
    branches:
      - main
  pull_request:
jobs:
  build-linux:
    name: build-linux
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Get latest CMake and ninja
      uses: lukka/get-cmake@latest
    - name: Run CMake
      run: cmake -B build -G "Ninja Multi-Config"
    - name: Build
      run: cmake --build build --config Release -j 8

  build-macosx:
    name: build-macosx
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v3
    - name: Run CMake
      run: cmake -B build -G "Ninja Multi-Config"
    - name: Build
      run: cmake --build build --config Release -j 8

  build-windows:
    name: build-windows
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v3
    - name: Run CMake
      run: cmake -B build -G "Visual Studio 17 2022" -A x64
    - name: Build
      run: cmake --build build --config Release
