name: Build
on:
  push:
    branches:
      - main
  pull_request:
jobs:
  build-linux:
    name: build-linux
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Install CMake and Ninja
        uses: lukka/get-cmake@latest
        with:
          cmakeVersion: latestrc
          ninjaVersion: latest
      - name: Build project
        run: |
            cmake -B build -G "Ninja Multi-Config"
            cmake --build build --config Release -j 8
  build-macosx:
    name: build-macosx
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Install CMake and Ninja
        uses: lukka/get-cmake@latest
        with:
          cmakeVersion: latestrc
          ninjaVersion: latest
      - name: Build project
        run: |
            cmake -B build -G "Ninja Multi-Config"
            cmake --build build --config Release -j 8
  build-windows:
    name: build-windows
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Install MSVC Build Tools
        uses: microsoft/setup-msbuild@v1.3.1
        with:
         include-prerelease: true

      - name: Build project
        run: |
#            cmake -B build -G "Visual Studio 17 2022" -A x64
#            cmake --build build --config Release
