name: Snyk Security

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  snyk:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write
      actions: read
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Snyk CLI
        uses: snyk/actions/setup@v1
        with:
          cli-version: '1.666.0'
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
      - name: Install dependencies
        run: |
          sudo apt-get update && sudo apt-get install -y gcc
      - name: Snyk test
        run: snyk test --file=. --severity-threshold=high --json | tee snyk_report.json
      - name: Upload results to Snyk
        if: always()
        uses: snyk/actions/upload-to-snyk@v1
        with:
          file: snyk_report.json
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
